<?php

namespace Database\Seeders;

use App\Models\Commune;
use App\Models\County;
use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // User::factory(10)->create();

        User::factory()->create([
            'username' => 'admin',
            'surname' => 'admin',
            'name' => 'admin',
            'role' => 10,
            'password' => Hash::make('abcd1234'),
            'county_id' => 3064,
            'commune_id' => 3064011,
            'accepted' => true,
            'email' => 'ggg@ggg.pl'
        ]);


        County::factory()->createMany([
            ['id' => '3001', 'name' => 'chodzieski', 'description' => 'Powiat Chodzieski', 'nr_dysp' => '301'],
            ['id' => '3002', 'name' => 'czarnkowsko-trzcianecki', 'description' => 'Powiat Czarnkowsko-Trzcianecki', 'nr_dysp' => '302'],
            ['id' => '3003', 'name' => 'gnieźnieński', 'description' => 'Powiat Gnieźnieński', 'nr_dysp' => '303'],
            ['id' => '3004', 'name' => 'gostyński', 'description' => 'Powiat Gostyński', 'nr_dysp' => '304'],
            ['id' => '3005', 'name' => 'grodziski', 'description' => 'Powiat Grodziski', 'nr_dysp' => '305'],
            ['id' => '3006', 'name' => 'jarociński', 'description' => 'Powiat Jarociński', 'nr_dysp' => '306'],
            ['id' => '3007', 'name' => 'kaliski', 'description' => 'Powiat Kaliski', 'nr_dysp' => '307'],
            ['id' => '3008', 'name' => 'kępiński', 'description' => 'Powiat Kępiński', 'nr_dysp' => '309'],
            ['id' => '3009', 'name' => 'kolski', 'description' => 'Powiat Kolski', 'nr_dysp' => '310'],
            ['id' => '3010', 'name' => 'koniński', 'description' => 'Powiat Koniński', 'nr_dysp' => '311'],
            ['id' => '3011', 'name' => 'kościański', 'description' => 'Powiat Kościański', 'nr_dysp' => '313'],
            ['id' => '3012', 'name' => 'krotoszyński', 'description' => 'Powiat Krotoszyński', 'nr_dysp' => '314'],
            ['id' => '3013', 'name' => 'leszczyński', 'description' => 'Powiat Leszczyński', 'nr_dysp' => '315'],
            ['id' => '3014', 'name' => 'międzychodzki', 'description' => 'Powiat Międzychodzki', 'nr_dysp' => '317'],
            ['id' => '3015', 'name' => 'nowotomyski', 'description' => 'Powiat Nowotomyski', 'nr_dysp' => '318'],
            ['id' => '3016', 'name' => 'obornicki', 'description' => 'Powiat Obornicki', 'nr_dysp' => '319'],
            ['id' => '3017', 'name' => 'ostrowski', 'description' => 'Powiat Ostrowski', 'nr_dysp' => '320'],
            ['id' => '3018', 'name' => 'ostrzeszowski', 'description' => 'Powiat Ostrzeszowski', 'nr_dysp' => '321'],
            ['id' => '3019', 'name' => 'pilski', 'description' => 'Powiat Pilski', 'nr_dysp' => '322'],
            ['id' => '3020', 'name' => 'pleszewski', 'description' => 'Powiat Pleszewski', 'nr_dysp' => '323'],
            ['id' => '3021', 'name' => 'poznański', 'description' => 'Powiat Poznański', 'nr_dysp' => '324'],
            ['id' => '3022', 'name' => 'rawicki', 'description' => 'Powiat Rawicki', 'nr_dysp' => '326'],
            ['id' => '3023', 'name' => 'słupecki', 'description' => 'Powiat Słupecki', 'nr_dysp' => '327'],
            ['id' => '3024', 'name' => 'szamotulski', 'description' => 'Powiat Szamotulski', 'nr_dysp' => '328'],
            ['id' => '3025', 'name' => 'średzki', 'description' => 'Powiat Średzki', 'nr_dysp' => '330'],
            ['id' => '3026', 'name' => 'śremski', 'description' => 'Powiat Śremski', 'nr_dysp' => '329'],
            ['id' => '3027', 'name' => 'turecki', 'description' => 'Powiat Turecki', 'nr_dysp' => '331'],
            ['id' => '3028', 'name' => 'wągrowiecki', 'description' => 'Powiat Wągrowiecki', 'nr_dysp' => '332'],
            ['id' => '3029', 'name' => 'wolsztyński', 'description' => 'Powiat Wolsztyński', 'nr_dysp' => '333'],
            ['id' => '3030', 'name' => 'wrzesiński', 'description' => 'Powiat Wrzesiński', 'nr_dysp' => '334'],
            ['id' => '3031', 'name' => 'złotowski', 'description' => 'Powiat Złotowski', 'nr_dysp' => '335'],
            ['id' => '3061', 'name' => 'M. Kalisz', 'description' => 'Miasto Kalisz ', 'nr_dysp' => '308'],
            ['id' => '3062', 'name' => 'M. Konin', 'description' => 'Miasto Konin ', 'nr_dysp' => '312'],
            ['id' => '3063', 'name' => 'M. Leszno', 'description' => 'Miasto Leszno ', 'nr_dysp' => '316'],
            ['id' => '3064', 'name' => 'M. Poznań', 'description' => 'Miasto Poznań ', 'nr_dysp' => '325'],
        ]);

        // Communes

        Commune::factory()->createMany([
            ['id' => '3009022', 'county_id' => '3009', 'nr_dysp' => '1', 'office' => 'UG', 'city' => 'Babiak', 'name' => 'Babiak'],
            ['id' => '3008012', 'county_id' => '3008', 'nr_dysp' => '2', 'office' => 'UG', 'city' => 'Baranów', 'name' => 'Baranów'],
            ['id' => '3019022', 'county_id' => '3019', 'nr_dysp' => '3', 'office' => 'UG', 'city' => 'Białośliwie', 'name' => 'Białosliwie'],
            ['id' => '3007012', 'county_id' => '3007', 'nr_dysp' => '4', 'office' => 'UG', 'city' => 'Blizanów', 'name' => 'Blizanów'],
            ['id' => '3022013', 'county_id' => '3022', 'nr_dysp' => '5', 'office' => 'UG', 'city' => 'Bojanowo', 'name' => 'Bojanowo'],
            ['id' => '3004013', 'county_id' => '3004', 'nr_dysp' => '6', 'office' => 'UG', 'city' => 'Borek Wlkp.', 'name' => 'Borek Wlkp.'],
            ['id' => '3008022', 'county_id' => '3008', 'nr_dysp' => '7', 'office' => 'UG', 'city' => 'Bralin', 'name' => 'Bralin'],
            ['id' => '3026012', 'county_id' => '3026', 'nr_dysp' => '8', 'office' => 'UG', 'city' => 'Brodnica', 'name' => 'Brodnica'],
            ['id' => '3027022', 'county_id' => '3027', 'nr_dysp' => '9', 'office' => 'UG', 'city' => 'Brudzew', 'name' => 'Brudzew'],
            ['id' => '3007022', 'county_id' => '3007', 'nr_dysp' => '10', 'office' => 'UG', 'city' => 'Brzeziny', 'name' => 'Brzeziny'],
            ['id' => '3001022', 'county_id' => '3001', 'nr_dysp' => '11', 'office' => 'UG', 'city' => 'Budzyń', 'name' => 'Budzyń'],
            ['id' => '3021033', 'county_id' => '3021', 'nr_dysp' => '12', 'office' => 'UMiG', 'city' => 'Buk', 'name' => 'Buk'],
            ['id' => '3007032', 'county_id' => '3007', 'nr_dysp' => '13', 'office' => 'UG', 'city' => 'Ceków Kolonia', 'name' => 'Ceków Kolonia'],
            ['id' => '3020012', 'county_id' => '3020', 'nr_dysp' => '14', 'office' => 'UG', 'city' => 'Chocz', 'name' => 'Chocz'],
            ['id' => '3009032', 'county_id' => '3009', 'nr_dysp' => '15', 'office' => 'UG', 'city' => 'Chodów', 'name' => 'Chodów'],
            ['id' => '3001032', 'county_id' => '3001', 'nr_dysp' => '16', 'office' => 'UG', 'city' => 'Chodzież', 'name' => 'Chodzież'],
            ['id' => '3014012', 'county_id' => '3014', 'nr_dysp' => '18', 'office' => 'UG', 'city' => 'Chrzypsko Wielkie', 'name' => 'Chrzypsko Wielkie'],
            ['id' => '3018012', 'county_id' => '3018', 'nr_dysp' => '19', 'office' => 'UG', 'city' => 'Czajków', 'name' => 'Czajków'],
            ['id' => '3002022', 'county_id' => '3002', 'nr_dysp' => '20', 'office' => 'UG', 'city' => 'Czarnków', 'name' => 'Czarnków'],
            ['id' => '3011023', 'county_id' => '3011', 'nr_dysp' => '22', 'office' => 'UG', 'city' => 'Czempiń', 'name' => 'Czempiń'],
            ['id' => '3020022', 'county_id' => '3020', 'nr_dysp' => '23', 'office' => 'UG', 'city' => 'Czermin', 'name' => 'Czermin'],
            ['id' => '3003023', 'county_id' => '3003', 'nr_dysp' => '24', 'office' => 'UG', 'city' => 'Czerniejewo', 'name' => 'Czerniejewo'],
            ['id' => '3021042', 'county_id' => '3021', 'nr_dysp' => '25', 'office' => 'UG', 'city' => 'Czerwonak', 'name' => 'Czerwonak'],
            ['id' => '3028022', 'county_id' => '3028', 'nr_dysp' => '26', 'office' => 'UG', 'city' => 'Damasławek', 'name' => 'Damasławek'],
            ['id' => '3009043', 'county_id' => '3009', 'nr_dysp' => '27', 'office' => 'UG', 'city' => 'Dąbie', 'name' => 'Dąbie'],
            ['id' => '3027033', 'county_id' => '3027', 'nr_dysp' => '28', 'office' => 'UG', 'city' => 'Dobra', 'name' => 'Dobra'],
            ['id' => '3020032', 'county_id' => '3020', 'nr_dysp' => '29', 'office' => 'UG', 'city' => 'Dobrzyca', 'name' => 'Dobrzyca'],
            ['id' => '3026025', 'county_id' => '3026', 'nr_dysp' => '30', 'office' => 'UMiG', 'city' => 'Dolsk', 'name' => 'Dolsk'],
            ['id' => '3025012', 'county_id' => '3025', 'nr_dysp' => '31', 'office' => 'UG', 'city' => 'Dominowo', 'name' => 'Dominowo'],
            ['id' => '3021052', 'county_id' => '3021', 'nr_dysp' => '32', 'office' => 'UG', 'city' => 'Dopiewo', 'name' => 'Dopiewo'],
            ['id' => '3018022', 'county_id' => '3018', 'nr_dysp' => '33', 'office' => 'UG', 'city' => 'Doruchów', 'name' => 'Doruchów'],
            ['id' => '3002032', 'county_id' => '3002', 'nr_dysp' => '34', 'office' => 'UG', 'city' => 'Drawsko', 'name' => 'Drawsko'],
            ['id' => '3024022', 'county_id' => '3024', 'nr_dysp' => '35', 'office' => 'UG', 'city' => 'Duszniki', 'name' => 'Duszniki'],
            ['id' => '3020042', 'county_id' => '3020', 'nr_dysp' => '36', 'office' => 'UG', 'city' => 'Gizałki', 'name' => 'Gizałki'],
            ['id' => '3003032', 'county_id' => '3003', 'nr_dysp' => '37', 'office' => 'UG', 'city' => 'Gniezno', 'name' => 'Gniezno'],
            ['id' => '3007042', 'county_id' => '3007', 'nr_dysp' => '39', 'office' => 'UG', 'city' => 'Godziesze Wielkie', 'name' => 'Godziesze Wielkie'],
            ['id' => '3010013', 'county_id' => '3010', 'nr_dysp' => '40', 'office' => 'UG', 'city' => 'Golina', 'name' => 'Golina'],
            ['id' => '3028033', 'county_id' => '3028', 'nr_dysp' => '41', 'office' => 'UMiG', 'city' => 'Gołańcz', 'name' => 'Gołańcz'],
            ['id' => '3020052', 'county_id' => '3020', 'nr_dysp' => '42', 'office' => 'UG', 'city' => 'Gołuchów', 'name' => 'Gołuchów'],
            ['id' => '3004023', 'county_id' => '3004', 'nr_dysp' => '43', 'office' => 'UG', 'city' => 'Gostyń', 'name' => 'Gostyń'],
            ['id' => '3018033', 'county_id' => '3018', 'nr_dysp' => '44', 'office' => 'UMiG', 'city' => 'Grabów nad Prosną', 'name' => 'Grabów nad Prosną'],
            ['id' => '3005012', 'county_id' => '3005', 'nr_dysp' => '45', 'office' => 'UG', 'city' => 'Granowo', 'name' => 'Granowo'],
            ['id' => '3010022', 'county_id' => '3010', 'nr_dysp' => '46', 'office' => 'UG', 'city' => 'Grodziec', 'name' => 'Grodziec'],
            ['id' => '3005023', 'county_id' => '3005', 'nr_dysp' => '47', 'office' => 'UM', 'city' => 'Grodzisk Wlkp.', 'name' => 'Grodzisk Wlkp.'],
            ['id' => '3009052', 'county_id' => '3009', 'nr_dysp' => '48', 'office' => 'UG', 'city' => 'Grzegorzew', 'name' => 'Grzegorzew'],
            ['id' => '3006012', 'county_id' => '3006', 'nr_dysp' => '49', 'office' => 'UG', 'city' => 'Jaraczewo', 'name' => 'Jaraczewo'],
            ['id' => '3006023', 'county_id' => '3006', 'nr_dysp' => '50', 'office' => 'UM', 'city' => 'Jarocin', 'name' => 'Jarocin'],
            ['id' => '3031023', 'county_id' => '3031', 'nr_dysp' => '51', 'office' => 'UMiG', 'city' => 'Jastrowie', 'name' => 'Jastrowie'],
            ['id' => '3022023', 'county_id' => '3022', 'nr_dysp' => '52', 'office' => 'UMiG', 'city' => 'Jutrosin', 'name' => 'Jutrosin'],
            ['id' => '3019032', 'county_id' => '3019', 'nr_dysp' => '53', 'office' => 'UG', 'city' => 'Kaczory', 'name' => 'Kaczory'],
            ['id' => '3005032', 'county_id' => '3005', 'nr_dysp' => '55', 'office' => 'UG', 'city' => 'Kamieniec', 'name' => 'Kamieniec'],
            ['id' => '3027042', 'county_id' => '3027', 'nr_dysp' => '56', 'office' => 'UG', 'city' => 'Kawęczyn', 'name' => 'Kawęczyn'],
            ['id' => '3010032', 'county_id' => '3010', 'nr_dysp' => '57', 'office' => 'UG', 'city' => 'Kazimierz Biskupi', 'name' => 'Kazimierz Biskupi'],
            ['id' => '3024032', 'county_id' => '3024', 'nr_dysp' => '58', 'office' => 'UG', 'city' => 'Kaźmierz', 'name' => 'Kaźmierz'],
            ['id' => '3008033', 'county_id' => '3008', 'nr_dysp' => '59', 'office' => 'UMiG', 'city' => 'Kępno', 'name' => 'Kępno'],
            ['id' => '3003042', 'county_id' => '3003', 'nr_dysp' => '60', 'office' => 'UG', 'city' => 'Kiszkowo', 'name' => 'Kiszkowo'],
            ['id' => '3010043', 'county_id' => '3010', 'nr_dysp' => '61', 'office' => 'UG', 'city' => 'Kleczew', 'name' => 'Kleczew'],
            ['id' => '3021062', 'county_id' => '3021', 'nr_dysp' => '62', 'office' => 'UG', 'city' => 'Kleszczewo', 'name' => 'Kleszczewo'],
            ['id' => '3003053', 'county_id' => '3003', 'nr_dysp' => '63', 'office' => 'UG', 'city' => 'Kłecko', 'name' => 'Kłecko'],
            ['id' => '3009063', 'county_id' => '3009', 'nr_dysp' => '64', 'office' => 'UMiG', 'city' => 'Kłodawa', 'name' => 'Kłodawa'],
            ['id' => '3018042', 'county_id' => '3018', 'nr_dysp' => '65', 'office' => 'UG', 'city' => 'Kobyla Góra', 'name' => 'Kobyla Góra'],
            ['id' => '3012023', 'county_id' => '3012', 'nr_dysp' => '66', 'office' => 'UG', 'city' => 'Kobylin', 'name' => 'Kobylin'],
            ['id' => '3030012', 'county_id' => '3030', 'nr_dysp' => '67', 'office' => 'UG', 'city' => 'Kołaczkowo', 'name' => 'Kołaczkowo'],
            ['id' => '3009072', 'county_id' => '3009', 'nr_dysp' => '68', 'office' => 'UG', 'city' => 'Koło', 'name' => 'Koło'],
            ['id' => '3021072', 'county_id' => '3021', 'nr_dysp' => '70', 'office' => 'UG', 'city' => 'Komorniki', 'name' => 'Komorniki'],
            ['id' => '3021083', 'county_id' => '3021', 'nr_dysp' => '72', 'office' => 'UM', 'city' => 'Kostrzyn', 'name' => 'Kostrzyn'],
            ['id' => '3011032', 'county_id' => '3011', 'nr_dysp' => '73', 'office' => 'UG', 'city' => 'Kościan', 'name' => 'Kościan'],
            ['id' => '3009082', 'county_id' => '3009', 'nr_dysp' => '75', 'office' => 'UG', 'city' => 'Kościelec', 'name' => 'Kościelec'],
            ['id' => '3006032', 'county_id' => '3006', 'nr_dysp' => '76', 'office' => 'UG', 'city' => 'Kotlin', 'name' => 'Kotlin'],
            ['id' => '3012033', 'county_id' => '3012', 'nr_dysp' => '77', 'office' => 'UMiG', 'city' => 'Koźmin Wlkp.', 'name' => 'Koźmin Wlkp.'],
            ['id' => '3007052', 'county_id' => '3007', 'nr_dysp' => '78', 'office' => 'UG', 'city' => 'Koźminek', 'name' => 'Koźminek'],
            ['id' => '3021093', 'county_id' => '3021', 'nr_dysp' => '79', 'office' => 'UM', 'city' => 'Kórnik', 'name' => 'Kórnik'],
            ['id' => '3031033', 'county_id' => '3031', 'nr_dysp' => '80', 'office' => 'UMiG', 'city' => 'Krajenka', 'name' => 'Krajenka'],
            ['id' => '3010052', 'county_id' => '3010', 'nr_dysp' => '81', 'office' => 'UG', 'city' => 'Kramsk', 'name' => 'Kramsk'],
            ['id' => '3018052', 'county_id' => '3018', 'nr_dysp' => '82', 'office' => 'UG', 'city' => 'Kraszewice', 'name' => 'Kraszewice'],
            ['id' => '3004033', 'county_id' => '3004', 'nr_dysp' => '83', 'office' => 'UM', 'city' => 'Krobia', 'name' => 'Krobia'],
            ['id' => '3012043', 'county_id' => '3012', 'nr_dysp' => '84', 'office' => 'UM', 'city' => 'Krotoszyn', 'name' => 'Krotoszyn'],
            ['id' => '3013012', 'county_id' => '3013', 'nr_dysp' => '85', 'office' => 'UG', 'city' => 'Krzemieniewo', 'name' => 'Krzemieniewo'],
            ['id' => '3025022', 'county_id' => '3025', 'nr_dysp' => '86', 'office' => 'UG', 'city' => 'Krzykosy', 'name' => 'Krzykosy'],
            ['id' => '3010062', 'county_id' => '3010', 'nr_dysp' => '87', 'office' => 'UG', 'city' => 'Krzymów', 'name' => 'Krzymów'],
            ['id' => '3011043', 'county_id' => '3011', 'nr_dysp' => '88', 'office' => 'UMiG', 'city' => 'Krzywiń', 'name' => 'Krzywiń'],
            ['id' => '3002043', 'county_id' => '3002', 'nr_dysp' => '89', 'office' => 'UM', 'city' => 'Krzyż Wlkp.', 'name' => 'Krzyż Wlkp.'],
            ['id' => '3026035', 'county_id' => '3026', 'nr_dysp' => '90', 'office' => 'UM', 'city' => 'Książ Wlkp.', 'name' => 'KsiążWlkp.'],
            ['id' => '3015012', 'county_id' => '3015', 'nr_dysp' => '91', 'office' => 'UG', 'city' => 'Kuślin', 'name' => 'Kuślin'],
            ['id' => '3014022', 'county_id' => '3014', 'nr_dysp' => '92', 'office' => 'UG', 'city' => 'Kwilcz', 'name' => 'Kwilcz'],
            ['id' => '3023022', 'county_id' => '3023', 'nr_dysp' => '93', 'office' => 'UG', 'city' => 'Lądek', 'name' => 'Lądek'],
            ['id' => '3031042', 'county_id' => '3031', 'nr_dysp' => '95', 'office' => 'UG', 'city' => 'Lipka', 'name' => 'Lipka'],
            ['id' => '3013022', 'county_id' => '3013', 'nr_dysp' => '96', 'office' => 'UG', 'city' => 'Lipno', 'name' => 'Lipno'],
            ['id' => '3007062', 'county_id' => '3007', 'nr_dysp' => '97', 'office' => 'UG', 'city' => 'Lisków', 'name' => 'Lisków'],
            ['id' => '3002052', 'county_id' => '3002', 'nr_dysp' => '98', 'office' => 'UG', 'city' => 'Lubasz', 'name' => 'Lubasz'],
            ['id' => '3021011', 'county_id' => '3021', 'nr_dysp' => '99', 'office' => 'UM', 'city' => 'Luboń', 'name' => 'Luboń'],
            ['id' => '3015023', 'county_id' => '3015', 'nr_dysp' => '100', 'office' => 'UMiG', 'city' => 'Lwówek', 'name' => 'Lwówek'],
            ['id' => '3008042', 'county_id' => '3008', 'nr_dysp' => '101', 'office' => 'UG', 'city' => 'Łęka Opatowska', 'name' => 'Łęka Opatowska'],
            ['id' => '3019045', 'county_id' => '3019', 'nr_dysp' => '102', 'office' => 'UM', 'city' => 'Łobżenica', 'name' => 'Łobżenica'],
            ['id' => '3003062', 'county_id' => '3003', 'nr_dysp' => '103', 'office' => 'UG', 'city' => 'Łubowo', 'name' => 'Łubowo'],
            ['id' => '3001011', 'county_id' => '3001', 'nr_dysp' => '17', 'office' => 'UM', 'city' => 'Chodzież', 'name' => 'm.Chodzież'],
            ['id' => '3002011', 'county_id' => '3002', 'nr_dysp' => '21', 'office' => 'UM', 'city' => 'Czarnków', 'name' => 'm.Czarnków'],
            ['id' => '3003011', 'county_id' => '3003', 'nr_dysp' => '38', 'office' => 'UM', 'city' => 'Gniezno', 'name' => 'm.Gniezno'],
            ['id' => '3009011', 'county_id' => '3009', 'nr_dysp' => '69', 'office' => 'UM', 'city' => 'Koło', 'name' => 'm.Koło'],
            ['id' => '3011011', 'county_id' => '3011', 'nr_dysp' => '74', 'office' => 'UM', 'city' => 'Kościan', 'name' => 'm.Kościan'],
            ['id' => '3017011', 'county_id' => '3017', 'nr_dysp' => '136', 'office' => 'UM', 'city' => 'Ostrów Wlkp.', 'name' => 'm.Ostrów Wlkp.'],
            ['id' => '3019011', 'county_id' => '3019', 'nr_dysp' => '142', 'office' => 'UM', 'city' => 'Piła', 'name' => 'm.Piła'],
            ['id' => '3061011', 'county_id' => '3061', 'nr_dysp' => '54', 'office' => 'UM', 'city' => 'Kalisz', 'name' => 'm.Kalisz'],
            ['id' => '3062011', 'county_id' => '3062', 'nr_dysp' => '71', 'office' => 'UM', 'city' => 'Konin', 'name' => 'm.Konin'],
            ['id' => '3063011', 'county_id' => '3063', 'nr_dysp' => '94', 'office' => 'UM', 'city' => 'Leszno', 'name' => 'm.Leszno'],
            ['id' => '3024011', 'county_id' => '3024', 'nr_dysp' => '124', 'office' => 'UM', 'city' => 'Obrzycko', 'name' => 'm.Obrzycko'],
            ['id' => '3064011', 'county_id' => '3064', 'nr_dysp' => '150', 'office' => 'UM', 'city' => 'Poznań', 'name' => 'm.Poznań'],
            ['id' => '3023011', 'county_id' => '3023', 'nr_dysp' => '174', 'office' => 'UM', 'city' => 'Słupca', 'name' => 'm.Słupca'],
            ['id' => '3027011', 'county_id' => '3027', 'nr_dysp' => '199', 'office' => 'UG', 'city' => 'Turek', 'name' => 'm.Turek'],
            ['id' => '3028011', 'county_id' => '3028', 'nr_dysp' => '204', 'office' => 'UM', 'city' => 'Wągrowiec', 'name' => 'm.Wągrowiec'],
            ['id' => '3031011', 'county_id' => '3031', 'nr_dysp' => '224', 'office' => 'UM', 'city' => 'Złotów', 'name' => 'm.Złotów'],
            ['id' => '3027052', 'county_id' => '3027', 'nr_dysp' => '104', 'office' => 'UG', 'city' => 'Malanów', 'name' => 'Malanów'],
            ['id' => '3001043', 'county_id' => '3001', 'nr_dysp' => '105', 'office' => 'UMiG', 'city' => 'Margonin', 'name' => 'Margonin'],
            ['id' => '3019052', 'county_id' => '3019', 'nr_dysp' => '106', 'office' => 'UG', 'city' => 'Miasteczko Krajeńskie', 'name' => 'Miasteczko Krajeńskie'],
            ['id' => '3015032', 'county_id' => '3015', 'nr_dysp' => '107', 'office' => 'UG', 'city' => 'Miedzichowo', 'name' => 'Miedzichowo'],
            ['id' => '3022033', 'county_id' => '3022', 'nr_dysp' => '108', 'office' => 'UG', 'city' => 'Miejska Górka', 'name' => 'MiejskaGórka'],
            ['id' => '3003072', 'county_id' => '3003', 'nr_dysp' => '109', 'office' => 'UG', 'city' => 'Mieleszyn', 'name' => 'Mieleszyn'],
            ['id' => '3028042', 'county_id' => '3028', 'nr_dysp' => '110', 'office' => 'UG', 'city' => 'Mieścisko', 'name' => 'Mieścisko'],
            ['id' => '3014033', 'county_id' => '3014', 'nr_dysp' => '111', 'office' => 'UMiG', 'city' => 'Międzychód', 'name' => 'Międzychód'],
            ['id' => '3018063', 'county_id' => '3018', 'nr_dysp' => '112', 'office' => 'UMiG', 'city' => 'Mikstat', 'name' => 'Mikstat'],
            ['id' => '3030023', 'county_id' => '3030', 'nr_dysp' => '113', 'office' => 'UG', 'city' => 'Miłosław', 'name' => 'Miłosław'],
            ['id' => '3021103', 'county_id' => '3021', 'nr_dysp' => '114', 'office' => 'UM', 'city' => 'Mosina', 'name' => 'Mosina'],
            ['id' => '3021113', 'county_id' => '3021', 'nr_dysp' => '115', 'office' => 'UMiG', 'city' => 'Murowana Goślina', 'name' => 'Murowana Goślina'],
            ['id' => '3007072', 'county_id' => '3007', 'nr_dysp' => '116', 'office' => 'UG', 'city' => 'Mycielin', 'name' => 'Mycielin'],
            ['id' => '3030033', 'county_id' => '3030', 'nr_dysp' => '117', 'office' => 'UMiG', 'city' => 'Nekla', 'name' => 'Nekla'],
            ['id' => '3003082', 'county_id' => '3003', 'nr_dysp' => '118', 'office' => 'UG', 'city' => 'Niechanowo', 'name' => 'Niechanowo'],
            ['id' => '3017023', 'county_id' => '3017', 'nr_dysp' => '119', 'office' => 'UG', 'city' => 'Nowe Miasto nad Wartą', 'name' => 'Nowe Skalmierzyce'],
            ['id' => '3025032', 'county_id' => '3025', 'nr_dysp' => '120', 'office' => 'UMiG', 'city' => 'Nowe Skalmierzyce', 'name' => 'NoweMiasto'],
            ['id' => '3015043', 'county_id' => '3015', 'nr_dysp' => '121', 'office' => 'UM', 'city' => 'Nowy Tomyśl', 'name' => 'Nowy Tomyśl'],
            ['id' => '3016013', 'county_id' => '3016', 'nr_dysp' => '122', 'office' => 'UM', 'city' => 'Oborniki', 'name' => 'Oborniki Wlkp.'],
            ['id' => '3024042', 'county_id' => '3024', 'nr_dysp' => '123', 'office' => 'UG', 'city' => 'Obrzycko', 'name' => 'Obrzycko'],
            ['id' => '3017033', 'county_id' => '3017', 'nr_dysp' => '125', 'office' => 'UMiG', 'city' => 'Odolanów', 'name' => 'Odolanów'],
            ['id' => '3031053', 'county_id' => '3031', 'nr_dysp' => '126', 'office' => 'UMiG', 'city' => 'Okonek', 'name' => 'Okonek'],
            ['id' => '3009092', 'county_id' => '3009', 'nr_dysp' => '127', 'office' => 'UG', 'city' => 'Olszówka', 'name' => 'Olszówka'],
            ['id' => '3015053', 'county_id' => '3015', 'nr_dysp' => '128', 'office' => 'UMiG', 'city' => 'Opalenica', 'name' => 'Opalenica'],
            ['id' => '3007082', 'county_id' => '3007', 'nr_dysp' => '129', 'office' => 'UG', 'city' => 'Opatówek', 'name' => 'Opatówek'],
            ['id' => '3023032', 'county_id' => '3023', 'nr_dysp' => '130', 'office' => 'UG', 'city' => 'Orchowo', 'name' => 'Orchowo'],
            ['id' => '3013033', 'county_id' => '3013', 'nr_dysp' => '131', 'office' => 'UMiG', 'city' => 'Osieczna', 'name' => 'Osieczna'],
            ['id' => '3009102', 'county_id' => '3009', 'nr_dysp' => '132', 'office' => 'UG', 'city' => 'Osiek Mały', 'name' => 'Osiek Mały'],
            ['id' => '3024053', 'county_id' => '3024', 'nr_dysp' => '133', 'office' => 'UMiG', 'city' => 'Ostroróg', 'name' => 'Ostroróg'],
            ['id' => '3023042', 'county_id' => '3023', 'nr_dysp' => '134', 'office' => 'UG', 'city' => 'Ostrowite', 'name' => 'Ostrowite'],
            ['id' => '3017042', 'county_id' => '3017', 'nr_dysp' => '135', 'office' => 'UG', 'city' => 'Ostrów Wlkp.', 'name' => 'Ostrów Wlkp.'],
            ['id' => '3018073', 'county_id' => '3018', 'nr_dysp' => '137', 'office' => 'UMiG', 'city' => 'Ostrzeszów', 'name' => 'Ostrzeszów'],
            ['id' => '3022042', 'county_id' => '3022', 'nr_dysp' => '138', 'office' => 'UG', 'city' => 'Pakosław', 'name' => 'Pakosław'],
            ['id' => '3008052', 'county_id' => '3008', 'nr_dysp' => '139', 'office' => 'UG', 'city' => 'Perzów', 'name' => 'Perzów'],
            ['id' => '3004042', 'county_id' => '3004', 'nr_dysp' => '140', 'office' => 'UG', 'city' => 'Pępowo', 'name' => 'Pępowo'],
            ['id' => '3004052', 'county_id' => '3004', 'nr_dysp' => '141', 'office' => 'UG', 'city' => 'Piaski', 'name' => 'Piaski'],
            ['id' => '3020063', 'county_id' => '3020', 'nr_dysp' => '143', 'office' => 'UMiG', 'city' => 'Pleszew', 'name' => 'Pleszew'],
            ['id' => '3024063', 'county_id' => '3024', 'nr_dysp' => '144', 'office' => 'UM', 'city' => 'Pniewy', 'name' => 'Pniewy'],
            ['id' => '3021123', 'county_id' => '3021', 'nr_dysp' => '145', 'office' => 'UMiG', 'city' => 'Pobiedziska', 'name' => 'Pobiedziska'],
            ['id' => '3004063', 'county_id' => '3004', 'nr_dysp' => '146', 'office' => 'UM', 'city' => 'Pogorzela', 'name' => 'Pogorzela'],
            ['id' => '3002062', 'county_id' => '3002', 'nr_dysp' => '147', 'office' => 'UG', 'city' => 'Połajewo', 'name' => 'Połajewo'],
            ['id' => '3004073', 'county_id' => '3004', 'nr_dysp' => '148', 'office' => 'UM', 'city' => 'Poniec', 'name' => 'Poniec'],
            ['id' => '3023052', 'county_id' => '3023', 'nr_dysp' => '149', 'office' => 'UG', 'city' => 'Powidz', 'name' => 'Powidz'],
            ['id' => '3009113', 'county_id' => '3009', 'nr_dysp' => '151', 'office' => 'UG', 'city' => 'Przedecz', 'name' => 'Przedecz'],
            ['id' => '3029012', 'county_id' => '3029', 'nr_dysp' => '152', 'office' => 'UG', 'city' => 'Przemęt', 'name' => 'Przemęt'],
            ['id' => '3017052', 'county_id' => '3017', 'nr_dysp' => '153', 'office' => 'UG', 'city' => 'Przygodzice', 'name' => 'Przygodzice'],
            ['id' => '3027062', 'county_id' => '3027', 'nr_dysp' => '154', 'office' => 'UG', 'city' => 'Przykona', 'name' => 'Przykona'],
            ['id' => '3021021', 'county_id' => '3021', 'nr_dysp' => '155', 'office' => 'UM', 'city' => 'Puszczykowo', 'name' => 'Puszczykowo'],
            ['id' => '3030043', 'county_id' => '3030', 'nr_dysp' => '156', 'office' => 'UMiG', 'city' => 'Pyzdry', 'name' => 'Pyzdry'],
            ['id' => '3005043', 'county_id' => '3005', 'nr_dysp' => '157', 'office' => 'UM', 'city' => 'Rakoniewice', 'name' => 'Rakoniewice'],
            ['id' => '3017063', 'county_id' => '3017', 'nr_dysp' => '158', 'office' => 'UM', 'city' => 'Raszków', 'name' => 'Raszków'],
            ['id' => '3022053', 'county_id' => '3022', 'nr_dysp' => '159', 'office' => 'UM', 'city' => 'Rawicz', 'name' => 'Rawicz'],
            ['id' => '3016023', 'county_id' => '3016', 'nr_dysp' => '160', 'office' => 'UM', 'city' => 'Rogoźno', 'name' => 'Rogoźno'],
            ['id' => '3021132', 'county_id' => '3021', 'nr_dysp' => '161', 'office' => 'UG', 'city' => 'Rokietnica', 'name' => 'Rokietnica'],
            ['id' => '3012052', 'county_id' => '3012', 'nr_dysp' => '162', 'office' => 'UG', 'city' => 'Rozdrażew', 'name' => 'Rozdrażew'],
            ['id' => '3008062', 'county_id' => '3008', 'nr_dysp' => '163', 'office' => 'UG', 'city' => 'Rychtal', 'name' => 'Rychtal'],
            ['id' => '3010073', 'county_id' => '3010', 'nr_dysp' => '164', 'office' => 'UM', 'city' => 'Rychwał', 'name' => 'Rychwał'],
            ['id' => '3016032', 'county_id' => '3016', 'nr_dysp' => '165', 'office' => 'UM', 'city' => 'Ryczywół', 'name' => 'Ryczywół'],
            ['id' => '3013043', 'county_id' => '3013', 'nr_dysp' => '166', 'office' => 'UMiG', 'city' => 'Rydzyna', 'name' => 'Rydzyna'],
            ['id' => '3010082', 'county_id' => '3010', 'nr_dysp' => '167', 'office' => 'UG', 'city' => 'Rzgów', 'name' => 'Rzgów'],
            ['id' => '3029022', 'county_id' => '3029', 'nr_dysp' => '168', 'office' => 'UG', 'city' => 'Siedlec', 'name' => 'Siedlec'],
            ['id' => '3014043', 'county_id' => '3014', 'nr_dysp' => '169', 'office' => 'UG', 'city' => 'Sieraków', 'name' => 'Sieraków'],
            ['id' => '3017072', 'county_id' => '3017', 'nr_dysp' => '170', 'office' => 'UG', 'city' => 'Sieroszewice', 'name' => 'Sieroszewice'],
            ['id' => '3028053', 'county_id' => '3028', 'nr_dysp' => '171', 'office' => 'UMiG', 'city' => 'Skoki', 'name' => 'Skoki'],
            ['id' => '3010092', 'county_id' => '3010', 'nr_dysp' => '172', 'office' => 'UG', 'city' => 'Skulsk', 'name' => 'Skulsk'],
            ['id' => '3023062', 'county_id' => '3023', 'nr_dysp' => '173', 'office' => 'UG', 'city' => 'Słupca', 'name' => 'Słupca'],
            ['id' => '3010103', 'county_id' => '3010', 'nr_dysp' => '175', 'office' => 'UM', 'city' => 'Sompolno', 'name' => 'Sompolno'],
            ['id' => '3017082', 'county_id' => '3017', 'nr_dysp' => '176', 'office' => 'UG', 'city' => 'Sośnie', 'name' => 'Sośnie'],
            ['id' => '3010112', 'county_id' => '3010', 'nr_dysp' => '177', 'office' => 'UG', 'city' => 'Stare Miasto', 'name' => 'Stare Miasto'],
            ['id' => '3007093', 'county_id' => '3007', 'nr_dysp' => '178', 'office' => 'UMiG', 'city' => 'Stawiszyn', 'name' => 'Stawiszyn'],
            ['id' => '3021143', 'county_id' => '3021', 'nr_dysp' => '179', 'office' => 'UM', 'city' => 'Stęszew', 'name' => 'Stęszew'],
            ['id' => '3023072', 'county_id' => '3023', 'nr_dysp' => '180', 'office' => 'UG', 'city' => 'Strzałkowo', 'name' => 'Strzałkowo'],
            ['id' => '3021152', 'county_id' => '3021', 'nr_dysp' => '181', 'office' => 'UG', 'city' => 'Suchy Las', 'name' => 'SuchyLas'],
            ['id' => '3012011', 'county_id' => '3012', 'nr_dysp' => '182', 'office' => 'UM', 'city' => 'Sulmierzyce', 'name' => 'Sulmierzyce'],
            ['id' => '3021163', 'county_id' => '3021', 'nr_dysp' => '183', 'office' => 'UMiG', 'city' => 'Swarzędz', 'name' => 'Swarzędz'],
            ['id' => '3001053', 'county_id' => '3001', 'nr_dysp' => '184', 'office' => 'UMiG', 'city' => 'Szamocin', 'name' => 'Szamocin'],
            ['id' => '3024073', 'county_id' => '3024', 'nr_dysp' => '185', 'office' => 'UMiG', 'city' => 'Szamotuły', 'name' => 'Szamotuły'],
            ['id' => '3007102', 'county_id' => '3007', 'nr_dysp' => '186', 'office' => 'UG', 'city' => 'Szczytniki', 'name' => 'Szczytniki'],
            ['id' => '3019062', 'county_id' => '3019', 'nr_dysp' => '187', 'office' => 'UG', 'city' => 'Szydłowo', 'name' => 'Szydłowo'],
            ['id' => '3010123', 'county_id' => '3010', 'nr_dysp' => '188', 'office' => 'UMiG', 'city' => 'Ślesin', 'name' => 'Ślesin'],
            ['id' => '3011053', 'county_id' => '3011', 'nr_dysp' => '189', 'office' => 'UM', 'city' => 'Śmigiel', 'name' => 'Śmigiel'],
            ['id' => '3026045', 'county_id' => '3026', 'nr_dysp' => '190', 'office' => 'UM', 'city' => 'Śrem', 'name' => 'Śrem'],
            ['id' => '3025043', 'county_id' => '3025', 'nr_dysp' => '191', 'office' => 'UM', 'city' => 'Środa Wlkp.', 'name' => 'ŚrodaWlkp.'],
            ['id' => '3013052', 'county_id' => '3013', 'nr_dysp' => '192', 'office' => 'UG', 'city' => 'Święciechowa', 'name' => 'Święciechowa'],
            ['id' => '3021172', 'county_id' => '3021', 'nr_dysp' => '193', 'office' => 'UG', 'city' => 'Tarnowo Podgórne', 'name' => 'TarnowoPodgórne'],
            ['id' => '3031062', 'county_id' => '3031', 'nr_dysp' => '194', 'office' => 'UG', 'city' => 'Tarnówka', 'name' => 'Tarnówka'],
            ['id' => '3002073', 'county_id' => '3002', 'nr_dysp' => '195', 'office' => 'UM', 'city' => 'Trzcianka', 'name' => 'Trzcianka'],
            ['id' => '3008072', 'county_id' => '3008', 'nr_dysp' => '196', 'office' => 'UG', 'city' => 'Trzcinica', 'name' => 'Trzcinica'],
            ['id' => '3003093', 'county_id' => '3003', 'nr_dysp' => '197', 'office' => 'UMiG', 'city' => 'Trzemeszno', 'name' => 'Trzemeszno'],
            ['id' => '3027073', 'county_id' => '3027', 'nr_dysp' => '198', 'office' => 'UMiG', 'city' => 'Tuliszków', 'name' => 'Tuliszków'],
            ['id' => '3027082', 'county_id' => '3027', 'nr_dysp' => '200', 'office' => 'UM', 'city' => 'Turek', 'name' => 'Turek'],
            ['id' => '3019075', 'county_id' => '3019', 'nr_dysp' => '201', 'office' => 'UMiG', 'city' => 'Ujście', 'name' => 'Ujście'],
            ['id' => '3028062', 'county_id' => '3028', 'nr_dysp' => '202', 'office' => 'UG', 'city' => 'Wapno', 'name' => 'Wapno'],
            ['id' => '3028072', 'county_id' => '3028', 'nr_dysp' => '203', 'office' => 'UG', 'city' => 'Wągrowiec', 'name' => 'Wągrowiec'],
            ['id' => '3002083', 'county_id' => '3002', 'nr_dysp' => '205', 'office' => 'UM', 'city' => 'Wieleń', 'name' => 'Wieleń'],
            ['id' => '3005053', 'county_id' => '3005', 'nr_dysp' => '206', 'office' => 'UMiG', 'city' => 'Wielichowo', 'name' => 'Wielichowo'],
            ['id' => '3010132', 'county_id' => '3010', 'nr_dysp' => '207', 'office' => 'UG', 'city' => 'Wierzbinek', 'name' => 'Wierzbinek'],
            ['id' => '3013062', 'county_id' => '3013', 'nr_dysp' => '208', 'office' => 'UG', 'city' => 'Wijewo', 'name' => 'Wijewo'],
            ['id' => '3010142', 'county_id' => '3010', 'nr_dysp' => '209', 'office' => 'UG', 'city' => 'Wilczyn', 'name' => 'Wilczyn'],
            ['id' => '3003103', 'county_id' => '3003', 'nr_dysp' => '210', 'office' => 'UMiG', 'city' => 'Witkowo', 'name' => 'Witkowo'],
            ['id' => '3027092', 'county_id' => '3027', 'nr_dysp' => '211', 'office' => 'UG', 'city' => 'Władysławów', 'name' => 'Władysławów'],
            ['id' => '3013072', 'county_id' => '3013', 'nr_dysp' => '212', 'office' => 'UG', 'city' => 'Włoszakowice', 'name' => 'Włoszakowice'],
            ['id' => '3029033', 'county_id' => '3029', 'nr_dysp' => '213', 'office' => 'UM', 'city' => 'Wolsztyn', 'name' => 'Wolsztyn'],
            ['id' => '3024083', 'county_id' => '3024', 'nr_dysp' => '214', 'office' => 'UMiG', 'city' => 'Wronki', 'name' => 'Wronki'],
            ['id' => '3030053', 'county_id' => '3030', 'nr_dysp' => '215', 'office' => 'UMiG', 'city' => 'Września', 'name' => 'Września'],
            ['id' => '3019085', 'county_id' => '3019', 'nr_dysp' => '216', 'office' => 'UM', 'city' => 'Wyrzysk', 'name' => 'Wyrzysk'],
            ['id' => '3019095', 'county_id' => '3019', 'nr_dysp' => '217', 'office' => 'UMiG', 'city' => 'Wysoka', 'name' => 'Wysoka'],
            ['id' => '3023083', 'county_id' => '3023', 'nr_dysp' => '218', 'office' => 'UM', 'city' => 'Zagórów', 'name' => 'Zagórów'],
            ['id' => '3031072', 'county_id' => '3031', 'nr_dysp' => '219', 'office' => 'UG', 'city' => 'Zakrzewo', 'name' => 'Zakrzewo'],
            ['id' => '3025052', 'county_id' => '3025', 'nr_dysp' => '220', 'office' => 'UG', 'city' => 'Zaniemyśl', 'name' => 'Zaniemyśl'],
            ['id' => '3015063', 'county_id' => '3015', 'nr_dysp' => '221', 'office' => 'UM', 'city' => 'Zbąszyń', 'name' => 'Zbąszyń'],
            ['id' => '3012063', 'county_id' => '3012', 'nr_dysp' => '222', 'office' => 'UMiG', 'city' => 'Zduny', 'name' => 'Zduny'],
            ['id' => '3031082', 'county_id' => '3031', 'nr_dysp' => '223', 'office' => 'UG', 'city' => 'Złotów', 'name' => 'Złotów'],
            ['id' => '3007112', 'county_id' => '3007', 'nr_dysp' => '225', 'office' => 'UG', 'city' => 'Żelazków', 'name' => 'Żelazków'],
            ['id' => '3006043', 'county_id' => '3006', 'nr_dysp' => '226', 'office' => 'UMG', 'city' => 'Żerków', 'name' => 'Żerków'],



        ]);



    }
}
